name: game_task
description: "Flutter game controller and coin animation"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/home_page/
     - assets/animation_page/
     - assets/home_page/action_button/
     - assets/home_page/arrow_button/
